### ISSUE TITLE
[DATASET REQUEST] Icelandic Winogrande

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#155]
**Describe the dataset**
Icelandic Winogrande is hosted [at this Hugging Face repo](https://huggingface.co/datasets/mideind/icelandic-winogrande) and consists of ~1.09k samples. It is a multiple choice coreference resolution dataset with two options, and has been recommended as challenging by native speakers.

**Rationale**
This is a high-quality dataset for a low-resource language. It would be put in the reasoning category, probably replacing HellaSwag-is, since the latter is machine translated. Since there are only 1k samples we can only use it for few-shot evaluation, however.

**Comment by gardarjuto** [comment]
Is this something that would make sense for us at Miðeind to implement or will you who are more familiar with the codebase add it?

**Comment by saattrupdan** [comment]
> Is this something that would make sense for us at Miðeind to implement or will you who are more familiar with the codebase add it?

I think adding it in is very quick, but the problem is really its size. Of course it would be fine as a test-only split, but we're currently aiming to also enable finetuning evaluation on generative tasks (for instance, QLoRA finetuning of decoder models or T5-finetuning), and it's unclear to me what we would do with test-only datasets in that case.

I mean, one tentative fix one could do is to keep this as a test split, and generate a synthetic training and validation split for the dataset, but that would probably be of a much lower standard, so not quite sure how to deal with it.

@gardarjuto I'm not sure exactly how much work it is for you guys, but do you think it would be possible to effectively double the dataset, to have 1024+256+1024 for train/val/test? Alternatively, we would have to split the dataset into very small splits, like 256+256+512, which would result in a large variance in test scores.

**Comment by gardarjuto** [comment]
Thanks for the answer @saattrupdan! 
Currently, unfortunately I would say that we don't have the resources to double the dataset size.

WinoGrande-style examples take a surprising amount of effort to construct since you both have to design a WinoGrad ambiguous sentence as well as carefully ensuring that it doesn't include biased language which would hint at the answer. For Icelandic, this is a painstakingly difficult process since gendered nouns, inflections and verb forms can very easily give away the answer for free if you're not careful. I'd estimate not less than 5 minutes per example, making for over 14 full 7-hour work days (as a lower bound) which is just not feasible for us at this time.

This difficulty of crafting Icelandic WinoGrande examples also means that any synthetic or machine translated data will almost invariably be so unusable that training on them is likely counterproductive, worse than doing nothing at all. I therefore suggest that we use this only for few-shot evaluation.
