### ISSUE TITLE
[BUG] Generative model finetuning when running evaluation

### ISSUE THREAD

**Issue by saattrupdan** [ScandEval/ScandEval#518]
But even when I set -dl nl the model seems to be finetuning,  is this a bug @saattrupdan ?

<img width="1246" alt="Screenshot 2024-09-08 at 18 16 42" src="https://github.com/user-attachments/assets/e98b6f2d-9106-4842-a608-d61e51bfa5c4">

_Originally posted by @usarth in https://github.com/ScandEval/ScandEval/issues/35#issuecomment-2336742017_

**Comment by saattrupdan** [comment]
@usarth Can you try running the evaluation with the `--verbose` and `--raise-errors` flags? It seems like it doesn't recognise that your model is generative properly.

**Comment by usarth** [comment]
Yeah it does seems to that it does not identify it as generative model. Because after evaluation as well generating tag is false. Quite weird seems it is just a fine-tuned version of gemma. What is more weird is that when i give the local path of the model it works as normal. But when I give the huggingface model id then it is not working properly

**Comment by usarth** [comment]
How can I force that the fine-tunining does not happen? This happened again when I was trying to benchmark the Euro-LLM https://huggingface.co/utter-project/EuroLLM-1.7B-Instruct can you try at yourself?

**Comment by saattrupdan** [comment]
Hi @usarth. I don't have a laptop on me until Wednesday, but one thing that might be wrong is if the pipeline tag hasn't been set to "text-generation". Of course, you can't change this for the latter model you mentioned, but can you try it on your own models?

If that works then it can get patched quite quickly at least.
